export const AVATAR = {
    body: { width: 60, height: 80, radius: 12 },
    leg: { height: 30, width: 4, spacing: 15, footRadius: 6 },
    arm: { length: 35, width: 4, handRadius: 5, dropY: 10 },
    face: { paddingX: 8, paddingY: 10, height: 50, radius: 8, eyeRadius: 3, eyeSpacing: 12, eyeOffsetY: 18 },
    namePlate: { paddingX: 5, height: 12, radius: 4, textPadding: 3, offsetY: 15 },
    colors: {
        limbs: '#333',
        face: 'white',
        faceOpacity: 0.9,
        namePlate: '#333',
        namePlateOpacity: 0.8,
        nameText: 'white',
        eyes: 'black',
        dust: '#A0896C',
        eyebrows: '#333',
        tear: '#6BB5FF',
    },
};

export const ANIMATION = {
    breathing: { amount: 3, duration: 2000 },
    walking: {
        armSwing: 15,
        legSwing: 20,
        footLift: 5,
        bodyBob: 3,
        stepDuration: 400,
    },
    running: {
        armSwing: 35,
        legSwing: 40,
        footLift: 12,
        bodyBob: 8,
        stepDuration: 180,
    },
    jumping: {
        crouchAmount: 10,
        jumpHeight: 60,
        crouchDuration: 150,
        launchDuration: 200,
        airDuration: 100,
        landDuration: 150,
        armRaise: 70,
        legTuck: 25,
        stretchY: 1.15,
        stretchX: 0.9,
        squashY: 0.75,
        squashX: 1.2,
        squashDuration: 100,
        recoverDuration: 300,
    },
    dancing: {
        bounce: 8,
        wiggle: 10,
        armWave: 60,
        legBend: 15,
        beatDuration: 300,
    },
    waving: {
        armRaise: 80,
        waveSwing: 25,
        waveDuration: 200,
        waveCount: 3,
    },
    blinking: {
        closeDuration: 50,
        openDuration: 50,
        closedDuration: 80,
        minInterval: 2000,
        maxInterval: 5000,
    },
    clapping: {
        armRaise: 45,
        clapDistance: 5,
        clapDuration: 150,
        clapCount: 4,
    },
    dust: {
        particleCount: 6,
        minSize: 3,
        maxSize: 8,
        spreadX: 40,
        riseY: 15,
        duration: 400,
    },
    sad: {
        slouch: 8,
        headTilt: 5,
        armDroop: 20,
        breathingSpeed: 3000,
        swayAmount: 2,
        swayDuration: 2500,
        tearInterval: 2000,
        tearDuration: 1000,
    },
    angry: {
        tense: 3,
        shake: 2,
        shakeDuration: 100,
        stompDuration: 300,
        fistClench: true,
        breathingSpeed: 800,
    },
    romance: {
        bubbleCount: 12,
        minSize: 10,      // Was 6, now 10
        maxSize: 28,      // Was 18, now 28
        riseDuration: 1500,
        spawnInterval: 200,
        horizontalDrift: 35,  // Slightly more drift for bigger hearts
        riseHeight: 120,      // Rise a bit higher
        colors: ['#FF69B4', '#FF4458', '#FFB6C1', '#FF7F7F', '#FF1493', '#E91E63'],
    },
    speechBubble: {
        backgroundColor: '#FFFFFF',
        borderColor: '#333333',
        borderWidth: 2,
        borderRadius: 10,
        textColor: '#333333',
        fontSize: 12,
        lineHeight: 16,
        paddingX: 10,
        paddingY: 8,
        pointerWidth: 12,
        pointerHeight: 8,
        offsetY: 15,
        maxWidth: 150,
        minWidth: 40,
        displayDuration: 2500,
    },
};
